num1 = int(input('Enter first number: '))
num2 = int(input('Enter second number: '))
print('Addition is = ', num1 + num2)
print('Substraction is = ', num1 - num2)
print('Multiplication is = ', num1 * num2)
print('Division is = ', num1 // num2)
